Bash revamp

diff --git a/bash_functions/require b/bash_functions/require
--- a/bash_functions/require
+++ b/bash_functions/require
@@ -4,19 +4,46 @@
 # Last modified: 1993-09-29
 # Public domain
 
+# Commentary:
+
+# These functions provide an interface based on the lisp implementation for
+# loading libraries when they are needed and eliminating redundant loading.
+# The basic idea is that each "package" (or set of routines, even if it is
+# only one function) registers itself with a symbol that marks a "feature"
+# as being "provided".  If later you "require" a given feature, you save
+# yourself the trouble of explicitly loading it again.
+#
+# At the bottom of each package, put a "provide foobar", so when another
+# package has a "require foobar", it gets loaded and registered as a
+# "feature" that won't need to get loaded again.  (See warning below for
+# reasons why provide should be put at the end.)
+#
+# The list of provided features are kept in the `FEATURES' variable, which
+# is not exported.  Care should be taken not to munge this in the shell.
+# The search path comes from a colon-separated `FPATH' variable.  It has no
+# default value and must be set by the user.
+#
+# Require uses `fpath_search', which works by scanning all of FPATH for a
+# file named the same as the required symbol but with a `.bash' appended to
+# the name.  If that is found, it is loaded.  If it is not, FPATH is
+# searched again for a file name the same as the feature (i.e. without any
+# extension).  Fpath_search may be useful for doing library filename
+# lookups in other functions (such as a `load' or `autoload' function).
+#
+# Warning: Because require ultimately uses the builtin `source' command to
+# read in files, it has no way of undoing the commands contained in the
+# file if there is an error or if no provide statement appeared (this
+# differs from the lisp implementation of require, which normally undoes
+# most of the forms that were loaded if the require fails).  Therefore, to
+# minize the number of problems caused by requiring a faulty package (such
+# as syntax errors in the source file) it is better to put the provide at
+# the end of the file, rather than at the beginning.
+
 # Code:
 
 # Exporting this variable would cause considerable lossage, since none of
 # the functions are exported (or at least, they're not guaranteed to be)
-# export -n FEATURES
-# export -n require_indent require_depth
-typeset +x FEATURES
-typeset +x require_indent require_depth
-
-: ${require_depth:=0}
-: ${require_indent:=1}
-
-# export require_depth require_indent
+export -n FEATURES
 
 #:docstring :
 # Null function.  Provided only so that one can put page breaks in source
@@ -24,26 +51,28 @@ typeset +x require_indent require_depth
 #:end docstring:
 #
 # (\\014 == C-l)
-#eval "function $(echo -e \\014) () { : }"
+# eval "function $(echo -e \\014) () { : }"
+
 
 #:docstring featurep:
 # Usage: featurep argument
 #
 # Returns 0 (true) if argument is a provided feature.  Returns 1 (false)
-# otherwise. 
+# otherwise.
 #:end docstring:
 
 ###;;;autoload
-function featurep()
+function featurep ()
 {
     local feature="$1"
 
     case " ${FEATURES} " in
-       *" ${feature} "* ) return 0 ;;
+	*" ${feature} "* ) return 0 ;;
     esac
 
     return 1
 }
+
 
 #:docstring provide:
 # Usage: provide symbol ...
@@ -52,18 +81,19 @@ function featurep()
 #:end docstring:
 
 ###;;;autoload
-function provide()
+function provide ()
 {
     local feature
 
     for feature in "$@" ; do
-       if ! featurep "${feature}" ; then
-          FEATURES="${FEATURES} ${feature} "
-       fi
+	if ! featurep "${feature}" ; then
+	    FEATURES="${FEATURES} ${feature}"
+	fi
     done
 
     return 0
 }
+
 
 #:docstring require:
 # Usage: require feature {file}
@@ -80,70 +110,28 @@ function provide()
 #
 # If the variable REQUIRE_FAILURE_FATAL is set, require will cause the
 # current shell invocation to exit, rather than merely return.  This may be
-# useful for a shell script that vitally depends on a package. 
+# useful for a shell script that vitally depends on a package.
 #
 #:end docstring:
 
 ###;;;autoload
-function require()
+function require ()
 {
-    local verbose=1
-    local standard=0
-    local unrequire=0
-
-    OPTIND=1
-    while getopts qrs opt
-        do
-	    case "$opt" in
-		r)  unrequire=1 ;;
-		q)  verbose=0 ;;
-		s)  standard=1 ;;
-                *)  echo "require: usage: require [-q] [-s] feature [path]" >&2
-		    return 1 ;;
-	    esac
-        done
- 
-    shift $(( $OPTIND - 1 ))
- 
     local feature="$1"
     local path="$2"
-    local version="$3"
-    local file
- 
-    [ $unrequire -eq 1 ] && unrequire $feature
+    local file=""
 
-    if featurep "${feature}" ; then
-	return 0
-    fi
-
-    [ $standard -ne 0 ] && path=${STD_FPATH:-unknown}
-
-    file=$(fpath_search -q "${feature}" "${path}")
-
-    require_features="${require_features} ${require_depth}:${feature}:${file}"
-
-    require_depth=$(($require_depth + $require_indent))
-
-    [ ! -z $file ] && source "${file}"
-
-    require_depth=$(($require_depth - $require_indent))
+    file=$(fpath_search "${feature}" "${path}") && source "${file}"
 
     if ! featurep "${feature}" ; then
-	if [ "${verbose}" = "1" ] ; then
-	    echo "require: ${feature}: feature was not provided." 1>&2
-	fi
+	echo "require: ${feature}: feature was not provided." 1>&2
 	if [ "${REQUIRE_FAILURE_FATAL+set}" = "set" ]; then
 	    exit 1
 	fi
 	return 1
-   fi
+    fi
 
-   if [ ${require_depth} -eq 0 ] ; then
-      require_debug "${require_features}"
-      require_features=""
-   fi
-
-   return 0
+    return 0
 }
 
 #:docstring fpath_search:
@@ -156,24 +144,8 @@ function require()
 #:end docstring:
 
 ###;;;autoload
-function fpath_search() 
+function fpath_search ()
 {
-    local verbose=1
-    local stanard=0
-
-    OPTIND=1
-    while getopts qs opt
-        do
-	    case "$opt" in
-		q)  verbose=0 ;;
-		s)  standard=1 ;;
-                *)  echo "fpath_search: usage: fpath_search [-q] name [path]" >&2
-		    return 1 ;;
-	    esac
-        done
- 
-    shift $(( $OPTIND - 1 ))
- 
     local name="$1"
     local path="$2"
     local suffix=".bash"
@@ -181,85 +153,31 @@ function fpath_search()
 
     if [ -z "${path}" ]; then path="${FPATH}"; fi
 
-    for file in "${name}${suffix}" "${name}" ; do
-       set -- $(IFS=':'
-                 set -- ${path}
-                 for p in "$@" ; do
-                    echo -n "${p:-.} "
-                 done)
+    for file in "${name}${suffix}" "${name}"; do
+	set -- $(IFS=':'
+		 set -- ${path}
+		 for p in "$@" ; do
+		     echo -n "${p:-.} "
+		 done)
 
-       while [ $# -ne 0 ]; do
-          #test -f "${1}/${file}" && { file="${1}/${file}"; break 2 }
-	  if test -f "${1}/${file}" ; then
-		file="${1}/${file}"
+	while [ $# -ne 0 ]; do
+	    if [[ -f "${1}/${file}" ]]; then
+		file="${1}/${file}";
 		break 2
-	  fi
-          shift
-       done
+	    fi
+	    shift
+	done
     done
 
     if [ $# -eq 0 ]; then
-       if [ "${verbose}" = "1" ] ; then
-           echo "fpath_search: ${name}: file not found in fpath" 1>&2
-       fi
-       return 1
+	echo "fpath_search: ${name}: file not found in fpath" 1>&2
+	return 1
     fi
 
     echo "${file}"
     return 0
 }
 
-function require_debug()
-{
-    [ -z "$REQUIRE_DEBUG" ] && return
-
-    local awk=awk
-    local print_filename=0
-
-    [ "$REQUIRE_DEBUG" = "2" ] && print_filename=2
-
-    case $SWT_HOST_TYPE in
-	sun4-solaris2)
-	    # sun4-solaris2 core dumps with awk??
-	    awk=nawk
-	    ;;
-	*)
-	    awk=awk
-	    ;;
-    esac
-
-    local f
-
-    for f in $@
-    do
-	if [ "$print_filename" = "2" ] ; then
-	    echo "${f}" | $awk -F: '{ printf "%*s%s (%s)\n", $1,"",$2,$3 }'
-	else
-	    echo "${f}" | $awk -F: '{ printf "%*s%s\n", $1,"",$2 }'
-	fi
-    done
-}
-
-# From: https://web.archive.org/web/20121022051228/http://codesnippets.joyent.com/posts/show/1816
-
-function _require_trim_ws() {
-    local var="$*"
-    # remove leading whitespace characters
-    var="${var#"${var%%[![:space:]]*}"}"
-    # remove trailing whitespace characters
-    var="${var%"${var##*[![:space:]]}"}"   
-    echo -n "$var"
-}
-
-function unrequire()
-{
-    FEATURES=$(_require_trim_ws "${FEATURES//$1/}")
-}
-
 provide require
 
-### Local Variables: ***
-### mode:sh ***
-### End: ***
-
-
+# require.bash ends here
